[build]
builder = "nixpacks"
buildCommand = "npm i -g pnpm@8.15.1 && pnpm install --no-frozen-lockfile && pnpm --filter @cpms/database exec prisma generate && pnpm --filter @cpms/database run build && pnpm --filter @cpms/api run build"

[deploy]
startCommand = "node apps/api/dist/main"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
numReplicas = 1
