[build]
builder = "nixpacks"
buildCommand = "corepack enable && corepack prepare pnpm@8.15.1 --activate && NODE_ENV=development pnpm install --no-frozen-lockfile && cd packages/database && npx prisma@5.22.0 generate && npx prisma@5.22.0 migrate deploy && cd ../.. && pnpm --filter @cpms/database build && cd packages/database && npx ts-node prisma/seed.ts && cd ../.. && pnpm --filter @cpms/api build"

[deploy]
startCommand = "cd apps/api && node dist/main"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
numReplicas = 1
